### PR TITLE
Update config.json - EO4EU Platform

### PR DESCRIPTION
**Pull request by christosebos**

### CODE REVIEW

**Comment by m-mohr** [comment]
Could you please enable CORS on your endpoints so that the browser-based clients can connect to your backend? See the openEO API specification for details.

**Comment by ny-christian** [comment]
Hi Mathias, the CORS Policy has been enabled on our endpoints and also fixed some small typos. We have tested on openeo editor and we have no issues. Please let us know if there any action left that we need to take.

**Comment by m-mohr** [comment]
Thanks for the update, I can connect now, too.

As I don't have credentials (and the openEO Hub neither), we get a 401 on /collections, /processes, /file_formats and /service_types.
That's allowed by the API, but if you want the openEO Hub to actually expose your offerings, these should be publicly available. Otherwise people will just see the name of your service but nothing more, which is usually not very interesting to users.

**Comment by christophfriedrich** [comment]
Note that crawling is done once every night (if this hasn't been changed since I was responsible for it), so unless Matthias initiates a crawl manually (which I think he just did as I already see the entry online), changes will only be visible the next day.

**Comment by ny-christian** [comment]
Allright Christoph, thank you for the update. I will make the required changes to open the endpoints  /collections, /processes, /file_formats and /service_types.

**Pull request merged**
